### PR TITLE
Revert java version to 13.0.2

### PR DESCRIPTION
**Pull request by AntonSherstiuk2020**
Java 14 is not supported, so the agent cannot start. Reverting to previous version.

### CODE REVIEW

**Comment by ghost** [comment]
[CLA assistant check](https://cla.gocd.org/gocd/docker-gocd-agent-ubuntu-18.04?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.gocd.org/gocd/docker-gocd-agent-ubuntu-18.04?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.gocd.org/check/gocd/docker-gocd-agent-ubuntu-18.04?pullRequest=3) it.</sub>

**Comment by marques-work** [comment]
@AntonSherstiuk2020 I'm not able to reproduce this. The 20.8.0 ubuntu 18.04 agent image starts up fine for me:

image

**Comment by marques-work** [comment]
@AntonSherstiuk2020 We no longer assert against an upper bound for JDK versions, so this shouldn't be possible:

https://github.com/gocd/gocd/blob/1e23a06e496205ced5f1a8e83d9b209fc0a290cb/jar-class-loader/src/main/java/com/thoughtworks/gocd/AssertJava.java#L25-L30

Unless you are talking about ubuntu 18.04 not supporting JDK 14, which I could not reproduce either in a docker container.

I'm going to close this PR and the associated issue gocd/gocd#8596 because I wasn't able to see this behavior on a clean docker run; JDK 14 seems to work just fine with these agents, unless you can demonstrate how to reproduce this on 20.8.0.

If you do run into this issue again, and can show us how to reliably reproduce it, feel free to open this issue again.

**Comment by AntonSherstiuk2020** [comment]
@marques-work thank you so much for investigating! We have successfully deployed the latest version. Not sure what the problem was with our environment, but it seems to have been transient. Sorry for the trouble.

**Pull request closed without merging**
